name:  Deploy

on:
  push:
    branches: [ main ]

jobs:
        
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        run: echo Deploying ...
