name:  Deploy

on:
  push:
    branches: [ main, test ]

jobs:
        
  deploy-test:
    name: Deploy to testing
    if: github.event.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploying into testing
        
  deploy-stag:
    name: Deploy to staging
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploying into staging
        
  deploy-prod:
    name: Deploy to production
    needs: [deploy-stag]
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploying into production
